# config/environments/development.yml
api_endpoint: "https://api.openweathermap.org/data/2.5/forecast"
cache_ttl: 300 # 5 minutes dev cache
log_level: debug
redis_url: "redis://localhost:6379/0"
concurrency: 5